# https://taskfile.dev
version: '3'

tasks:

  test:
    cmds:
      - go test -v -race ./...

  build:
    cmds:
      - go build -v -o "${HOME}/.local/bin" .

  release-create:
    cmds:
      - gh release create ${RELEASE} --generate-notes {{.CLI_ARGS}}
  
  release-upload:
    cmds:
      - gh release upload ${RELEASE} "${HOME}/.local/bin/sink" --clobber

  print-date:
    cmds:
      - echo "v{{ now | date "2006.02.01" }}"
