name: ci-build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/ci-build.yaml'
      - '**.go'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SINK_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ vars.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}
      - name: install taskfile.dev
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: download dependencies
        run: go mod download
      - name: test
        run: task test
      - name: build
        run: task build

