name: release

on:
  workflow_dispatch:
    inputs:
      release:
        description: release version
        required: true

permissions:
  contents: write 
  discussions: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event.inputs.release }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ vars.GO_VERSION }}
      - name: install taskfile.dev
        run: go install -v github.com/go-task/task/v3/cmd/task@latest
      - name: download dependencies
        run: go mod download
      - name: test
        run: task test
        env:
          GH_TOKEN: ${{ secrets.SINK_TOKEN }}
      - name: build
        run: task build
      - name: create-release
        run: task release-create -- -d -p
      - name: upload-sink
        run: task release-upload
